### ISSUE TITLE
Unable to Stream Video from Device

### ISSUE THREAD

**Issue by theastrowolfe** [opensensorhub/osh-android#16]
* Branch: sofwerx
* Hub distro: osh-sensiasoft
* Sensor: Video (MJPEG & H264)

Attempting to get one frame or stream video from hub returns HTTP ERROR 500.

Stacktrace:
```
2019-02-26 13:24:56.448 ERROR SOSService:478306e1 [qtp695290707-40] - Internal error while processing request
java.io.IOException: Cannot write response
        at org.sensorhub.impl.service.sos.SOSServlet.handleRequest(SOSServlet.java:1201)
        at org.vast.ows.sos.SOSServlet.handleRequest(SOSServlet.java:78)
        at org.vast.ows.server.OWSServlet.processRequest(OWSServlet.java:152)
        at org.vast.ows.server.OWSServlet.doGet(OWSServlet.java:110)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.sensorhub.impl.service.sos.SOSServlet.service(SOSServlet.java:708)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:561)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error while requesting provider data
        at org.sensorhub.impl.service.sos.video.MJPEGSerializer.write(MJPEGSerializer.java:72)
        at org.sensorhub.impl.service.sos.SOSServlet.writeCustomFormatStream(SOSServlet.java:2151)
        at org.sensorhub.impl.service.sos.SOSServlet.handleRequest(SOSServlet.java:1130)
        ... 40 common frames omitted
Caused by: java.lang.ClassCastException: [I cannot be cast to [B
        at org.sensorhub.impl.service.sos.video.MJPEGSerializer.write(MJPEGSerializer.java:54)
        ... 42 common frames omitted
```

**Comment by mikebotts** [comment]
Is this still a problem or is it resolved??
