### ISSUE TITLE
Cannot get video data

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-android#7]
Using the last release (1.2), and the last android apk, I can connect the phone to the osh server, data seems to be received but I cannot read video data. Here the different logs I have:

- Directly from chrome:
ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" version="1.1">
<ows:Exception exceptionCode="InvalidParameterValue" locator="format">
<ows:ExceptionText>Unsupported format video/x-motion-jpeg</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

- From fflplay:
ffplay "http://localhost:8181/sensorhub/sos?service=SOS&version=2.0&request=GetResult&offering=urn:android:device:caf661b4881b902c-sos&observedProperty=http://sensorml.com/ont/swe/property/VideoFrame&temporalFilter=phenomenonTime,now/2055-03-29T17:34:34.766Z"
 => this throws an exception:
```bash
2017-03-29 22:25:18.231 [qtp2004241740-256] WARN  HttpChannel - /sensorhub/sos?service=SOS&version=2.0&request=GetResult&offering=urn:android:device:caf661b4881b902c-sos&observedProperty=http://sensorml.com/ont/swe/property/VideoFrame&temporalFilter=phenomenonTime,now/2055-03-29T17:34:34.766Z
java.lang.IllegalStateException: Committed
	at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1253) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Response.sendError(Response.java:567) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.vast.ows.server.OWSServlet.processRequest(OWSServlet.java:233) ~[ows-framework-bindings-1.2.0.jar:na]
	at org.vast.ows.server.OWSServlet.doGet(OWSServlet.java:132) ~[ows-framework-bindings-1.2.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.sensorhub.impl.service.sos.SOSServlet.service(SOSServlet.java:689) ~[sensorhub-service-swe-1.2.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:259) ~[jetty-servlets-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:222) ~[jetty-servlets-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:470) ~[jetty-servlets-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:322) ~[jetty-servlets-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:292) ~[jetty-servlets-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[jetty-servlet-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) [jetty-server-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.7.v20150116.jar:9.2.7.v20150116]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

I have access to capabilities and data seems to be received when I click onto the refresh button to display observation outputs of the new created sensor.

```
Euler_orientation_data
Sampling Time = 2017-03-29T20:29:01.364Z
Orient
Yaw Angle = 26.79463005065918 deg
Pitch Angle = 0.0 deg
Roll Angle = 0.0 deg
Gps_data
Sampling Time
Location
Geodetic Latitude (deg)
Longitude (deg)
Altitude (m)
Camera0_data
Sampling Time = 2017-03-29T20:29:01.333Z
Img [600]
Row [800]
Pixel
Red
Green
Blue
```

This worked a couple of months ago. I've upgraded my android phone version to Nougat (android 7.0). It may cause the problem?

**Comment by alexrobin** [comment]
Can you try again with the latest version?
